baseURL: http://localhost
projectName: QVOTIDIE
scenarios:
  - name: Consulter les titres
    path: ./scenarios/consult_index.js
  - name: Consulter un article
    path: ./scenarios/consult_article.js
containers:
  - qvotidie-static_hosting-1
  - qvotidie-backend-1

