baseURL: http://localhost
projectName: QVOTIDIE
scenarios:
    - path: ./benchmark/scenario1.js
      name: Consulter les titres
    - path: ./benchmark/scenario2.js
      name: Consulter un article
containers:
  - qvotidie-static_hosting-1

