services:

  static_hosting:
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  backend:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
