services:

  static_hosting:
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  backend:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD

  accessible_backend:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        alias put="curl -X PUT -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'"
        put backend:5984/_node/nonode@nohost/_config/chttpd/enable_cors --data '"true"'
        put backend:5984/_node/nonode@nohost/_config/cors/origins --data '"*"'
        put backend:5984/qvotidie
        put backend:5984/qvotidie/_security --data '{"members":{"roles":[]},"admins":{"roles":["_admin"]}}'
